sudo: false
dist: xenial
group: stable

language: scala

## add the following jobs to the build matrix:
matrix:
  include:
  - jdk: openjdk8
    before_install:
      - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
    apt:
      packages:
        - openjdk8
  - jdk: openjdk11

script:
  - sbt "+ test"

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
