name: Scala

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [2.12.10, 2.13.1, 0.21.0-RC1]

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: openjdk@1.11.0
    - name: Scalafmt
      if: startsWith(matrix.scala, '2.13')
      run: sbt scalafmtSbtCheck scalafmtCheckAll
    - name: Run tests
      run: sbt ++${{matrix.scala}} test
